### ISSUE TITLE
Create CSW transaction tests using generator

### ISSUE THREAD

**Issue by JorgeMartinezG** [boundlessgeo/registry#1]
- [x] Single CSW-T transaction to add a record and verify that it can be accessed via GetRecord
 - [x] Multiple records in the same transaction (10).

No data files need to be added to the repo, let's create the test data dynamically.

**Comment by JorgeMartinezG** [comment]
Travis checks are failing when python 3.5 tests are performed. Check pr

https://github.com/boundlessgeo/registry/pull/5

**Comment by ingenieroariel** [comment]
Fixed.
