### ISSUE TITLE
items and tests to add

### ISSUE THREAD

**Issue by JorgeMartinezG** [boundlessgeo/registry#17]
This is a list of functions and tests, that need to be added in the future.
- catalogs search in tests. See #13
- Serializers: search_engine discrimination.
- search_api: Popular text (Including test)
- search_api: Popular users (Including test)
- request_time_facet for solr.
- parse time_gap in solr

**Comment by ingenieroariel** [comment]
We'll add them based on customer requirements + code coverage.
