### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/registry#20]
- [ ] Port API documentation
 - [ ] Create docs for MapProxy debugging
 - [x] Document General Architecture
 - [x] Developers introduction
 - [x] Installation instructions
 - [x] Test framework setup (assuming no Travis)

**Comment by ingenieroariel** [comment]
@JorgeMartinezG can you update the list on this PR based on the work you did yesterday?

**Comment by JorgeMartinezG** [comment]
@ingenieroariel I already created a PR. Please review

**Comment by ingenieroariel** [comment]
Thanks Jorge, I merged it - can you mark the items on this list that were done as done? Let's leave the ticket open if there are areas that you did not cover.

**Comment by ingenieroariel** [comment]
Closing this one and tracking API docs here: https://github.com/boundlessgeo/registry/issues/43
