### ISSUE TITLE
 No module named pytest

### ISSUE THREAD

**Issue by davisc** [boundlessgeo/registry#28]
user@ip:/srv/git/registry-master$ python -c "from test_registry import construct_payload; print construct_payload(records_number=10) > payload.xml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test_registry.py", line 2, in <module>
    import pytest
ImportError: No module named pytest

**Comment by ingenieroariel** [comment]
Those modules are automatically installed after you run:

`python setup.py test`
