### ISSUE TITLE
Write to ES on CSW-T transactions

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/registry#6]
When receiving a CSW-T transaction, write the information to the elasticsearch index. Using bulk when there are many records in the transaction.

The way to implement it is by overriding the need methods in the RegistryRepository, saving to elastic and calling `super()` afterwards.

**Comment by JorgeMartinezG** [comment]
Tests are not passing because there is no elasticsearch in travis. Which version should be used?

**Comment by ingenieroariel** [comment]
Fixed in master.
