### ISSUE TITLE
Make sure mapproxy configuration is correctly for loaded csw records

### ISSUE THREAD

**Issue by JorgeMartinezG** [boundlessgeo/registry#65]
Load ~1000 layers and test mapproxy response in registry

**Comment by ingenieroariel** [comment]
To be able to handle this we need the `dct:alternative` record to be present in CSW documents when ingesting. That field should have the WMS name or ESRI layer name.

https://github.com/geopython/pycsw/pull/488

**Comment by ingenieroariel** [comment]
For the frontend to be able to access the layer and add it to the map it needs a `tile_url` field, you can add it like this:

https://github.com/cga-harvard/HHypermap/blob/626d4f4ec07e6a3da8f417a0b93d85518cce9839/hypermap/aggregator/models.py#L603

**Comment by ingenieroariel** [comment]
@JorgeMartinezG  Please create screenshots with the working feature and close this one.

**Comment by JorgeMartinezG** [comment]
![image](https://cloud.githubusercontent.com/assets/3285923/20890806/49d5608e-bad6-11e6-90ff-ef58df4f03e6.png)
